version: "3"

services:
  vote:
    image: ${REGISTRY}/vote:${TAG}
    build: ./vote
    command: python app.py
    volumes:
     - ./vote:/app
    ports:
      - "5000:80"

  result:
    image: ${REGISTRY}/result:${TAG}
    build: ./result
    command: nodemon server.js
    volumes:
      - ./result:/app
    ports:
      - "5001:80"
      - "5858:5858"

  worker:
    image: ${REGISTRY}/worker:${TAG}
    build:
      context: ./worker

  redis-master:
    image: redis:alpine
    ports: ["6379"]

  postgres-postgresql:
    image: postgres:9.4
    volumes:
      - "db-data:/var/lib/postgresql/data"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=secret

volumes:
  db-data:
